### ISSUE TITLE
_printf函数和ftoa函数的错误

### ISSUE THREAD

**Issue by hy2z** [daizhirui/CamelStudio_Library#2]
- ftoa中itoa使用的同一个缓存数组，小数部分会覆盖掉整数内容，稍微改了下，我觉得用全局数组并不是一个好主意
```
char s[100] = {0};

char *ftoa(float a_fp) {
    _memset(s, 100, 0);
    char *p = s;
    itoa((int)a_fp, 10);
    _strcat(p, __convertBuffer);     // append decimal point
    _strcat(p, ".");
    // a_fp = FP_Abs(a_fp);
    int i = (a_fp - (int)a_fp) * 1000000;     // subtract to get the decimals, and multiply by 1000
    itoa(i, 10);                              // convert to a second string
    _strcat(p, __convertBuffer);
    return s;
}
```
- 可变参数传入float会被提升为double，解决方法有两个
 - 实现float和double转换
 - 用联合，传入value.int，在函数里处理value.float

**Comment by daizhirui** [comment]
Thanks for your feedback! This problem is already solved [Related commit].(https://github.com/daizhirui/CamelStudio_Library/commit/3e97745ffdb7231be2762f0ee7ed5e684bcae697)
Because the volume of flash is limited, it is better to use global array convertBuffer.
